#!/bin/bash
set -e -E -u

DOCKER_CLUSTERENV_HOME=${DOCKER_CLUSTERENV_HOME:-./docker-clusterenv}
HOSTNAME=${1:-receiver}
OUT_DIR=out/logs/$HOSTNAME
mkdir -p $OUT_DIR
touch $OUT_DIR/yadtreceiver.log

./update-targetfile

$DOCKER_CLUSTERENV_HOME/start-machine $HOSTNAME \
    --link-files=rootfs/receiver/etc/yadtshell:/etc \
    --link-files=rootfs/receiver/etc/yadt.conf.d:/etc \
    --link-files=$OUT_DIR/*.log:/var/log \
    --link-files=yadtcommons/src/main/python/*:_python_path_ \
    --link-files=fysom/src/main/python/*:_python_path_ \
    --link-files=yadtreceiver/src/main/scripts/*:/usr/bin \
    --link-files=yadtreceiver/src/main/python/*:_python_path_ \
    --link-files=yadtreceiver/src/main/python/yadtreceiver/yadtreceiver:/etc/init.d \
    --link-files=yadtreceiver/src/main/python/yadtreceiver/yadtreceiver.tac:/etc/twisted-taps \
    --link-files=yadtbroadcast-client/src/main/scripts/*:/usr/bin \
    --link-files=yadtbroadcast-client/src/main/python/*:_python_path_ \
    --link-files=hostexpand/src/main/scripts/*:/usr/bin \
    --link-files=hostexpand/src/main/python/*:_python_path_ \
    --link-files=yadt-minion/src/main/scripts/*:/usr/bin \
    --link-files=yadt-minion/src/main/python/*:_python_path_ \
    --link-files=yadtshell/src/main/scripts/*:/usr/bin \
    --link-files=yadtshell/src/main/python/*:_python_path_ \
    --post-init-machine=start-receiver-post-init
