#!/bin/bash
set -e -E -u

DOCKER_CLUSTERENV_HOME=${DOCKER_CLUSTERENV_HOME:-./docker-clusterenv}
HOSTNAME=${1:-ybc}
OUT_DIR=out/logs/$HOSTNAME

mkdir -p $OUT_DIR

$DOCKER_CLUSTERENV_HOME/start-machine $HOSTNAME \
    --port=8080:8080 \
    --port=8081:8081 \
    --link-files=rootfs/broadcaster/etc/yadt.conf.d:/etc \
    --link-files=rootfs/broadcaster/etc/yadtbroadcast-server/:/etc \
    --link-files=$OUT_DIR:/tmp/logs/broadcaster \
    --link-files=yadt-minion/src/main/scripts/*:/usr/bin \
    --link-files=yadt-minion/src/main/python/*:_python_path_ \
    --link-files=yadtbroadcast-server/src/main/scripts/*:/usr/bin \
    --link-files=yadtbroadcast-server/src/main/python/*:_python_path_ \
    --link-files=yadtbroadcast-service/src/etc/init.d/*:/etc/init.d \
    --link-files=yadtbroadcast-server-docroot/src/var/yadtbroadcast-server/*:/var/yadtbroadcast-server \
    --post-init-machine=start-broadcaster-post-init

