#!/bin/bash
set -e -E -u

DOCKER_CLUSTERENV_HOME=${DOCKER_CLUSTERENV_HOME:-./docker-clusterenv}

HOSTNAME=${1:-}

$DOCKER_CLUSTERENV_HOME/start-machine $HOSTNAME \
    --link-files=rootfs/minion/etc/yadt.conf.d:/etc \
    --link-files=rootfs/minion/etc/init.d/*:/etc/init.d \
    --link-files=yadt-minion/src/main/scripts/*:/usr/bin \
    --link-files=yadt-minion/src/main/python/*:_python_path_
