#!/bin/bash
set -e -E -u

DOCKER_CLUSTERENV_HOME=${DOCKER_CLUSTERENV_HOME:-../docker-clusterenv}
HOSTNAME=${1:-receiver}
OUT_DIR=out/logs/$HOSTNAME

cat <<EOTARGET > out/target
hosts:
- $(sed -n "s_^address=/__;T;s_/.*__;T;p" out/etc/dnsmasq.d/* | tr "\n" " ")
EOTARGET
mkdir -p $OUT_DIR

$DOCKER_CLUSTERENV_HOME/start-machine $HOSTNAME \
    --mount-dir=rootfs/receiver/etc/yadtshell:/etc/yadtshell:ro \
    --mount-dir=$OUT_DIR:/var/log:rw \
    --link-files=yadtcommons/src/main/python/*:_python_path_ \
    --link-files=yadtreceiver/src/main/scripts/*:/usr/bin \
    --link-files=yadtreceiver/src/main/python/*:_python_path_ \
    --link-files=yadtreceiver/src/main/python/yadtreceiver:/usr/bin \
    --link-files=yadtbroadcast-client/src/main/scripts/*:/usr/bin \
    --link-files=yadtbroadcast-client/src/main/python/*:_python_path_ \
    --link-files=hostexpand/src/main/scripts/*:/usr/bin \
    --link-files=hostexpand/src/main/python/*:_python_path_ \
    --link-files=yadtshell/src/main/scripts/*:/usr/bin \
    --link-files=yadtshell/src/main/python/*:_python_path_
