#!/bin/bash
set -u -e -E -o pipefail

SERVICE=$(basename $0)
CMD=$1
STATUS=/tmp/status-$SERVICE
EC=0

case "$CMD" in
    start)
        echo 0 > $STATUS
        sleep 1
        ;;
    stop)
        echo 3 > $STATUS
        sleep 1
        ;;
    status)
        EC=$(cat $STATUS 2> /dev/null) || EC=1
        ;;
esac

exit $EC
